language: python
python:
- '3.8'
install:
- pip install -q -r requirements.txt .
script:
- python setup.py install
notifications:
  email: false
deploy:
  provider: pypi
  username: "__token__"
  password: $PYPASS
  on:
    distributions: sdist bdist_wheel
    repo: archerysec/archerysec-cli
