deploy:
  provider: pypi
  user: archerysec
  password:
    secure: KamF7QeqwYLGEe6HapWOAKoIPt19aYH35K1/9YIFTACE+nHCpT158rnnDjj+Yo0D7PNUWzqwmqzKoUySrsnjs/7mpYSCkRtpVXCi2+Tpha4F4YaZkfELAGy8UT8NHtmwQLnxzMt6yLBGGeBf3rPxTzgNhQ3TA0n0bq3PL28gWbUdfg1pfjzlnmBns61aCrwl6yu46IYM9pzUOPAEEncQzaQ9B11FsfmQvrZXeaTS4rnfF9qfuvm6GnsZWsFxmvMa0NZ51CpX8crUchi4ADZFjpt7PZxwW3ipBDPwB65Q1D6CElt/9Cg/8YnIyYCaxx21GEjmgcO5C8M2JvzzS4ooYj2jGGelfbWMoEdqIke0XC1jtfsuiUm0hT3zKXQzEcJjaCgjqAAiww127nkVu4wcPyqGt9H3UUgFpXluofnK2zLFB3oZUBEyNlrqjB2yOmQBESygHY5P1HzT+DX0TwHmQyjIJH53FpcWNMGMuZI/9tDowSSHarhgySgHT5X7uvaaFmia1SlKEUd+nDoEkvEPhP9VZLZT6ZCHq8WXHh+Unp0xNJAyZsmquBadpb7B7bF53MdFcm7e5jfR+DNVxtAFhjcIAtO+HQYdDGANw6ZPYW6wXjz7b6J9mi6mDK46Dq53kY3R0bV9qSXyC2jjDmUkwR8CgvsLPa6oeFbw2tRrqUM=
  on:
    branch: master
