language: python
python: '2.7'
env:
- TOXENV=py35
- TOXENV=flake8
- TOXENV=docs
install:
- pip install tox
script:
- tox
deploy:
  provider: pypi
  user: archerysec
  distributions: sdist bdist_wheel
  password:
    secure:
  on:
    tags: true
    repo: archerysec/archerysec-cli
    condition: "$TOXENV = py35"